2nd

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -1,27 +1,32 @@
-name: changelog_updates
+# Fail PR if the there is no changelog entry
+
+name: Changelog entry verification
+
 on:
   pull_request:
-    branches: [master]
+    # Change to master before merging
+    branches: [ master ]
 
-    workflow_dispatch:
-      jobs:
-        build:
-          #name: Verify Changelog file updated
-          runs-on: ububtu-latest
+  workflow_dispatch:
 
-          steps:
-          - name: Checkout
-            uses: actions/checkout@v2
-            with:
-              fetch-depth: 2
-          - name: Verify Changed Changelog
-              uses: tj-actions/verify-changed-files@v12
-              id: verify-changed-files
-              with:
-                files: |
-                  CHANGELOG.md
-                - name: Run step only when files change.
-                  if: steps.verify-changed-files.outputs.files_changed == 'false'
-                  run: |
-                    exit 1
-                    echo "Changelog doesnt contain new entry, please update the changes done in this PR"
+jobs:
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Verify Changed Changelog
+        uses: tj-actions/verify-changed-files@v7.1
+        id: verify-changed-files
+        with:
+          files: |
+            CHANGELOG.md
+      - name: Run step only when files change.
+        if: steps.verify-changed-files.outputs.files_changed == 'false'
+        run: |
+          exit 1
+          echo "Changelog doesnt contain new entry, please update the changes done in this PR"
